#!/usr/bin/env python
# -*-Python-*-

import re, sys, random

random.seed(sys.argv[1])
D = int(sys.argv[2])

args = map(int, sys.argv[3:])
for NC, NR in zip(args[::2], args[1::2]):
    print NR
    roads = set([])
    for i in xrange(NR):
        c1 = c2 = random.randint(1, NC)
        while c1 == c2 or (c1, c2) in roads:
            c2 = random.randint(1, NC)
        roads.add((c1,c2))
        roads.add((c2,c1))
        print "C" + str(c1), "C" + str(c2), random.randint(1, D)
print 0
